server.port=8093

spring.application.name=ms-pedidos

spring.datasource.url=jdbc:mysql://localhost:${DB_PORT:3308}/bd_pedidos?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info

# URL directo al servicio de avisos (Node.js, no registrado en Eureka)
avisos.service.url=http://localhost:8094

