server.port=8080

spring.application.name=api-gateway

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true
spring.cloud.gateway.server.webflux.actuator.enabled=true

# Rutas del API Gateway

spring.cloud.gateway.server.webflux.routes[0].id=usuarios-autenticacion
spring.cloud.gateway.server.webflux.routes[0].uri=lb://MS-USUARIOS-ACCESO
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/autenticacion/**

spring.cloud.gateway.server.webflux.routes[1].id=clientes
spring.cloud.gateway.server.webflux.routes[1].uri=lb://MS-CLIENTES
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/clientes/**

spring.cloud.gateway.server.webflux.routes[2].id=catalogo-productos
spring.cloud.gateway.server.webflux.routes[2].uri=lb://MS-CATALOGO-PRODUCTOS
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/catalogo/**

spring.cloud.gateway.server.webflux.routes[3].id=pagos
spring.cloud.gateway.server.webflux.routes[3].uri=lb://MS-PAGOS-VALIDACION
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/pagos/**

spring.cloud.gateway.server.webflux.routes[4].id=envios
spring.cloud.gateway.server.webflux.routes[4].uri=lb://MS-ENVIOS
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/envios/**

spring.cloud.gateway.server.webflux.routes[5].id=transportistas
spring.cloud.gateway.server.webflux.routes[5].uri=lb://MS-TRANSPORTISTAS-RUTAS
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/transportistas/**

spring.cloud.gateway.server.webflux.routes[6].id=rutas
spring.cloud.gateway.server.webflux.routes[6].uri=lb://MS-TRANSPORTISTAS-RUTAS
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/rutas/**

# Ruta al BFF
spring.cloud.gateway.server.webflux.routes[7].id=bff-fachada-interfaz
spring.cloud.gateway.server.webflux.routes[7].uri=lb://BFF-FACHADA-INTERFAZ
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/bff/**

spring.cloud.gateway.server.webflux.routes[8].id=bodegas
spring.cloud.gateway.server.webflux.routes[8].uri=lb://MS-BODEGAS-UBICACIONES
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/bodegas/**,/api/ubicaciones/**

spring.cloud.gateway.server.webflux.routes[9].id=inventario
spring.cloud.gateway.server.webflux.routes[9].uri=lb://MS-INVENTARIO
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/api/inventario/**

spring.cloud.gateway.server.webflux.routes[10].id=pedidos
spring.cloud.gateway.server.webflux.routes[10].uri=lb://MS-PEDIDOS
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/api/pedidos/**

spring.cloud.gateway.server.webflux.routes[11].id=integracion-avisos
spring.cloud.gateway.server.webflux.routes[11].uri=http://localhost:8094
spring.cloud.gateway.server.webflux.routes[11].predicates[0]=Path=/api/avisos/**